//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class ParallelGripperCommandGoal : Message
    {
        public const string k_RosMessageName = "control_msgs/ParallelGripperCommand";
        public override string RosMessageName => k_RosMessageName;

        //  Parallel grippers refer to an end effector where two opposing fingers grasp an object from opposite sides.
        public Sensor.JointStateMsg command;
        //  name: the name(s) of the joint this command is requesting
        //  position: desired position of each gripper joint (radians or meters)
        //  velocity: (optional, not used if empty) max velocity of the joint allowed while moving (radians or meters / second)
        //  effort: (optional, not used if empty) max effort of the joint allowed while moving (Newtons or Newton-meters)

        public ParallelGripperCommandGoal()
        {
            this.command = new Sensor.JointStateMsg();
        }

        public ParallelGripperCommandGoal(Sensor.JointStateMsg command)
        {
            this.command = command;
        }

        public static ParallelGripperCommandGoal Deserialize(MessageDeserializer deserializer) => new ParallelGripperCommandGoal(deserializer);

        private ParallelGripperCommandGoal(MessageDeserializer deserializer)
        {
            this.command = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "ParallelGripperCommandGoal: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
