//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class ParallelGripperCommandResult : Message
    {
        public const string k_RosMessageName = "control_msgs/ParallelGripperCommand";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg state;
        //  The current gripper state.
        //  position of each joint (radians or meters)
        //  optional: velocity of each joint (radians or meters / second)
        //  optional: effort of each joint (Newtons or Newton-meters)
        public bool stalled;
        //  True if the gripper is exerting max effort and not moving
        public bool reached_goal;
        //  True if the gripper position has reached the commanded setpoint

        public ParallelGripperCommandResult()
        {
            this.state = new Sensor.JointStateMsg();
            this.stalled = false;
            this.reached_goal = false;
        }

        public ParallelGripperCommandResult(Sensor.JointStateMsg state, bool stalled, bool reached_goal)
        {
            this.state = state;
            this.stalled = stalled;
            this.reached_goal = reached_goal;
        }

        public static ParallelGripperCommandResult Deserialize(MessageDeserializer deserializer) => new ParallelGripperCommandResult(deserializer);

        private ParallelGripperCommandResult(MessageDeserializer deserializer)
        {
            this.state = Sensor.JointStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.stalled);
            deserializer.Read(out this.reached_goal);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.stalled);
            serializer.Write(this.reached_goal);
        }

        public override string ToString()
        {
            return "ParallelGripperCommandResult: " +
            "\nstate: " + state.ToString() +
            "\nstalled: " + stalled.ToString() +
            "\nreached_goal: " + reached_goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
