//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class ParallelGripperCommandFeedback : Message
    {
        public const string k_RosMessageName = "control_msgs/ParallelGripperCommand";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.JointStateMsg state;
        //  The current gripper state.
        //  position of each joint (radians or meters)
        //  optional: velocity of each joint (radians or meters / second)
        //  optional: effort of each joint (Newtons or Newton-meters)

        public ParallelGripperCommandFeedback()
        {
            this.state = new Sensor.JointStateMsg();
        }

        public ParallelGripperCommandFeedback(Sensor.JointStateMsg state)
        {
            this.state = state;
        }

        public static ParallelGripperCommandFeedback Deserialize(MessageDeserializer deserializer) => new ParallelGripperCommandFeedback(deserializer);

        private ParallelGripperCommandFeedback(MessageDeserializer deserializer)
        {
            this.state = Sensor.JointStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ParallelGripperCommandFeedback: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
