//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class DynamicInterfaceGroupValuesMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/DynamicInterfaceGroupValues";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  List of interface group names , e.g. ["flange_analog_IOs", "flange_vacuum"]
        public string[] interface_groups;
        //  Key-value pairs representing interfaces and their corresponding values for each interface group listed in `interface_groups`
        public InterfaceValueMsg[] interface_values;

        public DynamicInterfaceGroupValuesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.interface_groups = new string[0];
            this.interface_values = new InterfaceValueMsg[0];
        }

        public DynamicInterfaceGroupValuesMsg(Std.HeaderMsg header, string[] interface_groups, InterfaceValueMsg[] interface_values)
        {
            this.header = header;
            this.interface_groups = interface_groups;
            this.interface_values = interface_values;
        }

        public static DynamicInterfaceGroupValuesMsg Deserialize(MessageDeserializer deserializer) => new DynamicInterfaceGroupValuesMsg(deserializer);

        private DynamicInterfaceGroupValuesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.interface_groups, deserializer.ReadLength());
            deserializer.Read(out this.interface_values, InterfaceValueMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.interface_groups);
            serializer.Write(this.interface_groups);
            serializer.WriteLength(this.interface_values);
            serializer.Write(this.interface_values);
        }

        public override string ToString()
        {
            return "DynamicInterfaceGroupValuesMsg: " +
            "\nheader: " + header.ToString() +
            "\ninterface_groups: " + System.String.Join(", ", interface_groups.ToList()) +
            "\ninterface_values: " + System.String.Join(", ", interface_values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
