//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class MultiDOFStateStampedMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/MultiDOFStateStamped";
        public override string RosMessageName => k_RosMessageName;

        //  This message presents current controller state of multiple degrees of freedom.
        //  Header timestamp should be update time of controller state
        public Std.HeaderMsg header;
        public SingleDOFStateMsg[] dof_states;

        public MultiDOFStateStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.dof_states = new SingleDOFStateMsg[0];
        }

        public MultiDOFStateStampedMsg(Std.HeaderMsg header, SingleDOFStateMsg[] dof_states)
        {
            this.header = header;
            this.dof_states = dof_states;
        }

        public static MultiDOFStateStampedMsg Deserialize(MessageDeserializer deserializer) => new MultiDOFStateStampedMsg(deserializer);

        private MultiDOFStateStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.dof_states, SingleDOFStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.dof_states);
            serializer.Write(this.dof_states);
        }

        public override string ToString()
        {
            return "MultiDOFStateStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ndof_states: " + System.String.Join(", ", dof_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
