//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class QueryTrajectoryState_RequestMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/QueryTrajectoryState_Request";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg time;

        public QueryTrajectoryState_RequestMsg()
        {
            this.time = new BuiltinInterfaces.TimeMsg();
        }

        public QueryTrajectoryState_RequestMsg(BuiltinInterfaces.TimeMsg time)
        {
            this.time = time;
        }

        public static QueryTrajectoryState_RequestMsg Deserialize(MessageDeserializer deserializer) => new QueryTrajectoryState_RequestMsg(deserializer);

        private QueryTrajectoryState_RequestMsg(MessageDeserializer deserializer)
        {
            this.time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
        }

        public override string ToString()
        {
            return "QueryTrajectoryState_RequestMsg: " +
            "\ntime: " + time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
