//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class QueryCalibrationState_ResponseMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/QueryCalibrationState_Response";
        public override string RosMessageName => k_RosMessageName;

        public bool is_calibrated;

        public QueryCalibrationState_ResponseMsg()
        {
            this.is_calibrated = false;
        }

        public QueryCalibrationState_ResponseMsg(bool is_calibrated)
        {
            this.is_calibrated = is_calibrated;
        }

        public static QueryCalibrationState_ResponseMsg Deserialize(MessageDeserializer deserializer) => new QueryCalibrationState_ResponseMsg(deserializer);

        private QueryCalibrationState_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_calibrated);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_calibrated);
        }

        public override string ToString()
        {
            return "QueryCalibrationState_ResponseMsg: " +
            "\nis_calibrated: " + is_calibrated.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
