//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class QueryCalibrationState_RequestMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/QueryCalibrationState_Request";
        public override string RosMessageName => k_RosMessageName;


        public QueryCalibrationState_RequestMsg()
        {
        }
        public static QueryCalibrationState_RequestMsg Deserialize(MessageDeserializer deserializer) => new QueryCalibrationState_RequestMsg(deserializer);

        private QueryCalibrationState_RequestMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "QueryCalibrationState_RequestMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
