//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Control
{
    [Serializable]
    public class SingleDOFStateStampedMsg : Message
    {
        public const string k_RosMessageName = "control_msgs/SingleDOFStateStamped";
        public override string RosMessageName => k_RosMessageName;

        //  This message presents current controller state of one degree of freedom.
        //  Header timestamp should be update time of controller state
        public Std.HeaderMsg header;
        public SingleDOFStateMsg dof_state;

        public SingleDOFStateStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.dof_state = new SingleDOFStateMsg();
        }

        public SingleDOFStateStampedMsg(Std.HeaderMsg header, SingleDOFStateMsg dof_state)
        {
            this.header = header;
            this.dof_state = dof_state;
        }

        public static SingleDOFStateStampedMsg Deserialize(MessageDeserializer deserializer) => new SingleDOFStateStampedMsg(deserializer);

        private SingleDOFStateStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.dof_state = SingleDOFStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.dof_state);
        }

        public override string ToString()
        {
            return "SingleDOFStateStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ndof_state: " + dof_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
